---
- name: create consul directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ec2-user
  with_items:
    - "{{ consul_config_dir }}"
    - "{{ consul_config.data_dir }}"

- name: create main configuration file
  copy:
    dest: "{{ consul_config_dir }}/00-main.json"
    content: "{{ consul_config | to_nice_json(indent=2) }}"
