---
- name: download consul archive
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: /tmp/consul.zip

- name: extract consul archive
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin/
    remote_src: true
