---
- name: Create service consul
  template:
    src: ../templates/etc/systemd/system/consul.service.j2
    dest: /etc/systemd/system/consul.service

- name: Enable service consul
  service:
    name: consul
    enabled: true
